name: Check that things work
on: ['push']

jobs:
  lint_and_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: development
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      - name: Install packages
        run: bun install --frozen-lockfile
      - name: Lint
        run: bun run lint
      - run: bun run generate
        env:
          GOOGLE_FIREBASE_API_KEY: '${{ secrets.GOOGLE_FIREBASE_API_KEY }}'
          GOOGLE_FIREBASE_APP_ID: '${{ secrets.GOOGLE_FIREBASE_APP_ID }}'
          GOOGLE_FIREBASE_MESSAGING_ID: '${{ secrets.GOOGLE_FIREBASE_MESSAGING_ID }}'
          GOOGLE_FIREBASE_MEASUREMENT_ID: '${{ secrets.GOOGLE_FIREBASE_MEASUREMENT_ID }}'
          GOOGLE_FIREBASE_APP_CHECK_SITE_KEY: '${{ secrets.GOOGLE_FIREBASE_APP_CHECK_SITE_KEY }}'
